import {
  LayoutDashboard, Coins, Wallet, Bell, User, Settings, Shield,
  ExternalLink, LogOut, Menu, X, Search, Sun, Moon, Plus, Trash2,
  Edit, Check, ChevronLeft, ChevronRight, ChevronDown, Eye, EyeOff,
  Copy, CheckCircle, XCircle, AlertTriangle, Info, Download,
  FileText, TrendingUp, Users, Calendar, Lock, Key, Smartphone,
  Mail, Phone, MapPin, Globe, Filter, ArrowUp, ArrowDown, Loader2,
  MessageCircle,  // ✅ AJOUT pour WhatsApp
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Tontines: Coins,
  Payments: Wallet,
  Notifications: Bell,
  Profile: User,
  Settings: Settings,
  Admin: Shield,
  External: ExternalLink,
  Logout: LogOut,
  Menu: Menu,
  Close: X,
  Search: Search,
  Sun: Sun,
  Moon: Moon,
  Plus: Plus,
  Delete: Trash2,
  Edit: Edit,
  Check: Check,
  Back: ChevronLeft,
  Next: ChevronRight,
  Down: ChevronDown,
  Eye: Eye,
  EyeOff: EyeOff,
  Copy: Copy,
  Success: CheckCircle,
  Error: XCircle,
  Warning: AlertTriangle,
  Info: Info,
  Download: Download,
  File: FileText,
  Trending: TrendingUp,
  Users: Users,
  Calendar: Calendar,
  Lock: Lock,
  Key: Key,
  Phone: Smartphone,
  Mail: Mail,
  PhoneCall: Phone,
  Location: MapPin,
  Globe: Globe,
  Filter: Filter,
  Up: ArrowUp,
  DownArrow: ArrowDown,
  Loading: Loader2,
  WhatsApp: MessageCircle,  // ✅ AJOUT
};